import type { Crop, Product, User } from "@/types"

export const mockUser: User = {
  id: "1",
  email: "farmer@norifarm.com",
  name: "Alex Green",
  avatar: "/placeholder.svg?height=40&width=40",
  joinedAt: new Date("2024-01-15"),
  totalCrops: 12,
  totalHarvests: 8,
  level: 5,
  experience: 2450,
}

export const mockCrops: Crop[] = [
  {
    id: "1",
    name: "Heritage Tomatoes",
    type: "vegetable",
    plantedAt: new Date("2024-10-01"),
    harvestAt: new Date("2024-12-15"),
    maturityLevel: 85,
    isReady: false,
    imageUrl: "/placeholder.svg?height=200&width=200",
    description: "Premium heritage tomatoes with rich flavor",
    expectedYield: 5,
    rarity: "rare",
    nftTokenId: "NFT001",
  },
  {
    id: "2",
    name: "Golden Corn",
    type: "grain",
    plantedAt: new Date("2024-09-15"),
    harvestAt: new Date("2024-11-20"),
    maturityLevel: 100,
    isReady: true,
    imageUrl: "/placeholder.svg?height=200&width=200",
    description: "Sweet golden corn ready for harvest",
    expectedYield: 8,
    rarity: "common",
    nftTokenId: "NFT002",
  },
  {
    id: "3",
    name: "Dragon Fruit Cactus",
    type: "fruit",
    plantedAt: new Date("2024-08-01"),
    harvestAt: new Date("2025-02-01"),
    maturityLevel: 45,
    isReady: false,
    imageUrl: "/placeholder.svg?height=200&width=200",
    description: "Exotic dragon fruit with stunning appearance",
    expectedYield: 3,
    rarity: "legendary",
    nftTokenId: "NFT003",
  },
  {
    id: "4",
    name: "Fresh Basil",
    type: "herb",
    plantedAt: new Date("2024-10-20"),
    harvestAt: new Date("2024-12-01"),
    maturityLevel: 95,
    isReady: false,
    imageUrl: "/placeholder.svg?height=200&width=200",
    description: "Aromatic basil perfect for cooking",
    expectedYield: 2,
    rarity: "common",
    nftTokenId: "NFT004",
  },
]

export const mockProducts: Product[] = [
  {
    id: "p1",
    name: "Organic Tomato Seeds - Heritage Variety",
    description: "Premium heritage tomato seeds for your next planting season",
    price: 12.99,
    originalPrice: 15.99,
    imageUrl: "/placeholder.svg?height=150&width=150",
    category: "Seeds",
    brand: "GreenThumb",
    rating: 4.8,
    reviewCount: 124,
    inStock: true,
    retailer: "walmart",
    productUrl: "#",
    relatedCropTypes: ["vegetable"],
  },
  {
    id: "p2",
    name: "Premium Garden Trowel",
    description: "Durable stainless steel trowel for all your gardening needs",
    price: 24.99,
    imageUrl: "/placeholder.svg?height=150&width=150",
    category: "Tools",
    brand: "GardenPro",
    rating: 4.6,
    reviewCount: 89,
    inStock: true,
    retailer: "walmart",
    productUrl: "#",
    relatedCropTypes: ["vegetable", "fruit", "herb"],
  },
  {
    id: "p3",
    name: "Organic Fertilizer Mix",
    description: "All-natural fertilizer blend for healthy crop growth",
    price: 18.99,
    originalPrice: 22.99,
    imageUrl: "/placeholder.svg?height=150&width=150",
    category: "Fertilizer",
    brand: "EcoGrow",
    rating: 4.7,
    reviewCount: 156,
    inStock: true,
    retailer: "walmart",
    productUrl: "#",
    relatedCropTypes: ["vegetable", "fruit", "grain", "herb"],
  },
]
