import type { Crop, Product, User } from "@/types"

export const mockUser: User = {
  id: "1",
  email: "farmer@norifarm.com",
  name: "Alex Green",
  avatar: "/placeholder.svg?height=40&width=40",
  joinedAt: new Date("2024-01-15"),
  totalCrops: 12,
  totalHarvests: 8,
  level: 5,
  experience: 2450,
}

export const mockCrops: Crop[] = [
  {
    id: "1",
    name: "Heritage Tomatoes",
    type: "vegetable",
    plantedAt: new Date("2024-10-01"),
    harvestAt: new Date("2024-12-15"),
    maturityLevel: 85,
    isReady: false,
    imageUrl: "/placeholder.svg?height=200&width=200",
    description: "Premium heritage tomatoes with rich flavor",
    expectedYield: 5,
    rarity: "rare",
    nftTokenId: "NFT001",
  },
  {
    id: "2",
    name: "Golden Corn",
    type: "grain",
    plantedAt: new Date("2024-09-15"),
    harvestAt: new Date("2024-11-20"),
    maturityLevel: 100,
    isReady: true,
    imageUrl: "/placeholder.svg?height=200&width=200",
    description: "Sweet golden corn ready for harvest",
    expectedYield: 8,
    rarity: "common",
    nftTokenId: "NFT002",
  },
  {
    id: "3",
    name: "Dragon Fruit Cactus",
    type: "fruit",
    plantedAt: new Date("2024-08-01"),
    harvestAt: new Date("2025-02-01"),
    maturityLevel: 45,
    isReady: false,
    imageUrl: "/placeholder.svg?height=200&width=200",
    description: "Exotic dragon fruit with stunning appearance",
    expectedYield: 3,
    rarity: "legendary",
    nftTokenId: "NFT003",
  },
  {
    id: "4",
    name: "Fresh Basil",
    type: "herb",
    plantedAt: new Date("2024-10-20"),
    harvestAt: new Date("2024-12-01"),
    maturityLevel: 95,
    isReady: false,
    imageUrl: "/placeholder.svg?height=200&width=200",
    description: "Aromatic basil perfect for cooking",
    expectedYield: 2,
    rarity: "common",
    nftTokenId: "NFT004",
  },
  {
    id: "5",
    name: "Tomato",
    type: "vegetable",
    plantedAt: new Date("2024-10-15"),
    harvestAt: new Date("2024-12-20"),
    maturityLevel: 90,
    isReady: false,
    imageUrl: "/placeholder.svg?height=200&width=200",
    description: "Classic red tomatoes perfect for cooking",
    expectedYield: 6,
    rarity: "common",
    nftTokenId: "NFT124",
  },
]

export const mockProducts: Product[] = [
  {
    id: "p1",
    name: "Fresh Organic Tomato Box",
    description: "Premium organic tomatoes, 2kg box from local Korean farms",
    price: 19000,
    originalPrice: 22000,
    imageUrl: "https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=400",
    category: "Fresh Produce",
    brand: "농협마트",
    rating: 4.8,
    reviewCount: 124,
    inStock: true,
    retailer: "walmart",
    productUrl: "https://norifarm-shop.com/product/tomato-box-123",
    relatedCropTypes: ["vegetable"],
  },
  {
    id: "p2",
    name: "Premium Korean Corn Box",
    description: "Sweet Korean corn, 10 ears per box, freshly harvested",
    price: 15000,
    imageUrl: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400",
    category: "Fresh Produce",
    brand: "제주농산",
    rating: 4.7,
    reviewCount: 89,
    inStock: true,
    retailer: "walmart",
    productUrl: "https://norifarm-shop.com/product/korean-corn-456",
    relatedCropTypes: ["grain"],
  },
  {
    id: "p3",
    name: "Dragon Fruit Fresh Pack",
    description: "Exotic dragon fruit, 3 pieces, imported from premium farms",
    price: 28000,
    originalPrice: 32000,
    imageUrl: "https://images.unsplash.com/photo-1526318472351-c75fcf070305?w=400",
    category: "Exotic Fruits",
    brand: "프리미엄과일",
    rating: 4.9,
    reviewCount: 67,
    inStock: true,
    retailer: "amazon",
    productUrl: "https://norifarm-shop.com/product/dragon-fruit-789",
    relatedCropTypes: ["fruit"],
  },
  {
    id: "p4",
    name: "Fresh Basil Herb Bundle",
    description: "Organic fresh basil, perfect for Korean-Italian fusion cooking",
    price: 8000,
    imageUrl: "https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=400",
    category: "Fresh Herbs",
    brand: "허브팜",
    rating: 4.6,
    reviewCount: 43,
    inStock: true,
    retailer: "target",
    productUrl: "https://norifarm-shop.com/product/fresh-basil-321",
    relatedCropTypes: ["herb"],
  },
  {
    id: "p5",
    name: "Organic Tomato Seeds - Heritage Variety",
    description: "Premium heritage tomato seeds for your next planting season",
    price: 12000,
    originalPrice: 15000,
    imageUrl: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400",
    category: "Seeds",
    brand: "씨앗나라",
    rating: 4.8,
    reviewCount: 124,
    inStock: true,
    retailer: "walmart",
    productUrl: "https://norifarm-shop.com/product/tomato-seeds-654",
    relatedCropTypes: ["vegetable"],
  },
  {
    id: "p6",
    name: "Premium Garden Trowel",
    description: "Durable stainless steel trowel for all your gardening needs",
    price: 24000,
    imageUrl: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400",
    category: "Tools",
    brand: "가든프로",
    rating: 4.6,
    reviewCount: 89,
    inStock: true,
    retailer: "walmart",
    productUrl: "https://norifarm-shop.com/product/garden-trowel-987",
    relatedCropTypes: ["vegetable", "fruit", "herb"],
  },
  {
    id: "p7",
    name: "Organic Fertilizer Mix",
    description: "All-natural fertilizer blend for healthy crop growth",
    price: 18000,
    originalPrice: 22000,
    imageUrl: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400",
    category: "Fertilizer",
    brand: "에코그로우",
    rating: 4.7,
    reviewCount: 156,
    inStock: true,
    retailer: "walmart",
    productUrl: "https://norifarm-shop.com/product/organic-fertilizer-147",
    relatedCropTypes: ["vegetable", "fruit", "grain", "herb"],
  },
]
